apiVersion: v1
kind: ServiceAccount
metadata:
  name: snapshoter
  namespace: weaviate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: snapshoter-role
  namespace: weaviate
rules:
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshots"]
  verbs: ["create", "get", "list"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: snapshoter-binding
  namespace: weaviate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: snapshoter-role
subjects:
- kind: ServiceAccount
  name: snapshoter
  namespace: weaviate
